apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:postgresql://database1.cfyiqsgkgikw.us-east-1.rds.amazonaws.com:5432/restaurantdb
  foodcataloguedb_url: jdbc:postgresql://database1.cfyiqsgkgikw.us-east-1.rds.amazonaws.com:5432/foodcataloguedb
  userdb_url: jdbc:postgresql://database1.cfyiqsgkgikw.us-east-1.rds.amazonaws.com:5432/userdb
  orderdb_url: mongodb+srv://admin:admin@cluster1.who2uff.mongodb.net/orderdb?retryWrites=true&w=majority&appName=Cluster1
  eureka_service_address: http://eureka-0.eureka-service.default.svc.cluster.local:8082/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  